<?php
/**
 * Magiccart 
 * @category  Magiccart 
 * @copyright   Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license   http://www.magiccart.net/license-agreement.html
 * @Author: Magiccart<team.magiccart@gmail.com>
 * @@Create Date: 2014-09-10 10:21:05
 * @@Modify Date: 2016-06-14 15:04:17
 * @@Function:
 */
?>
<!--
<?php 	
if(! Mage::getStoreConfig('magicslider/general/enabled')) return;
$bannerCollection = $this->_getCollection();
if(($bannerCollection->count())<=0) return;
$imageCollection = $this->_getMagicsliderImageCollection($bannerCollection); 		
$width  = $this->getData('width');
$height = $this->getData('height');
$idHtml = $this->generateRandomString();
?>
<?php foreach ($imageCollection as $item) : ?>
	<?php 
		$content = $item['content']; 		
		$images = $this->getSortedImages($content);
	?>
	<?php if(isset($images) && !empty($images) && count($images)>0) : ?>
		<div class="magicslider">
			<div id="<?php echo $idHtml ?>">
			<?php $start = 'play start' ?>
			<?php foreach($images as $image): ?>
				<div class="item">
					<a  href="<?php echo ( isset($image['link']) && $image['link'] ) ? ($image['link']) : '#'; ?>">
						<img src="<?php echo $this->helper('magicslider')->resizeImg($image['file'], $width, $height);?>" alt="<?php echo $image['label'] ? $image['label'] : 'magicslider' ?>">
					</a>
					<?php if(isset($image['html']) && $image['html']) : ?>
						<div class="bx-caption <?php echo $start ?>">
							<?php echo $image['html'] ?>
						</div>
					<?php endif ?>
				</div>
				<?php $start = '' ?>
			<?php endforeach;?>
			</div>
		</div>

	<?php endif;?>
<?php endforeach;?>-->

<style>
	.btn-img {
    width: 25px;
    height: 45px;
    display: inline-block;
    background-repeat: no-repeat;    
    background-position: center;
    background-color: transparent;    
    vertical-align: middle;
}

.img-small{
	width: 12px;
    height: 24px;
}

.img-right-arrow {
    background-image: url(skin/frontend/aloelectro/default/images/images/right_arrow.png);
    background-size: 100% 100%;
	position: absolute;
	top: 40%;
}

.img-left-arrow {
    background-image: url(skin/frontend/aloelectro/default/images/images/left_arrow.png);
    background-size: 100% 100%;
	position: absolute;
	top: 40%;
	left: 30%;
}

.carousel-control.right, .carousel-control.left{
	background-image: none;
}

.carousel-indicators{
	z-index: 1;
}

.carousel-indicators li{
	background-color: #fff;
}

.carousel-indicators .active{
	background-color: #FF2A00;
	border-color: #FF2A00;
}

.carousel-inner .item img{
	height: 300px;
}

.shop-now{
	position: absolute;
    top: 75%;
    left: 25.5%;
    padding: 4px 25px;
    color: white;
    background-color: #FF2A00;
    border-radius: 8px;
    font-size: 12px;
    font-weight: bold;
}

.shop-now.white{
	color: black;
    background-color: #fff;
}

.shop-now:hover{
	color: white;
}

.shop-now.white:hover{
	color: black;
}

.center-nav-tab{
	text-align:center;
	margin-top:5px;
}

.center-nav-tab .nav.nav-tabs{
	display: inline-block;
    border: none;
}

.center-nav-tab .nav-tabs>li>a{
	padding: 4px 24px;
	font-size: 18px;
	font-weight: bold;
}

.center-nav-tab .nav-tabs>li.active>a, 
.center-nav-tab .nav-tabs>li.active>a:hover, 
.center-nav-tab .nav-tabs>li.active>a:focus {
    color: #fff;
    cursor: default;
    background-color: #FF2A00;
    border: 1px solid #FF2A00;
    border-bottom-color: none;
	border-radius: 0;
}

.tcb-product-item .tcb-product-photo img{
	display: inline-block;
	overflow: hidden;
	border-radius: 50%;
	border: 1px solid #dedede;
	height: 9.15vw;
}

.tcb-product-item .product-name-1{
	color: black;
	font-weight: bold;
	font-size: 12px;
}
@media screen and (min-width: 768px){
	.carousel-indicators {
		bottom: 0px;
	}
}
</style>

<div class="container">
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
	  <li data-target="#myCarousel" data-slide-to="3"></li>
      <li data-target="#myCarousel" data-slide-to="4"></li>
      <li data-target="#myCarousel" data-slide-to="5"></li>
	  <li data-target="#myCarousel" data-slide-to="6"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <img src="skin/frontend/aloelectro/default/images/images/slides/slide1.png" alt="slide1" style="width:100%;">
		<a class="shop-now" href = "#">SHOP NOW</a>
      </div>
      <div class="item">
        <img src="skin/frontend/aloelectro/default/images/images/slides/slide2.png" alt="slide2" style="width:100%;">
		<a class="shop-now" href = "#">SHOP NOW</a>
	  </div>
    
      <div class="item">
        <img src="skin/frontend/aloelectro/default/images/images/slides/slide3.png" alt="slide3" style="width:100%;">
		<a class="shop-now" href = "#">SHOP NOW</a>
	  </div>

	  <div class="item">
        <img src="skin/frontend/aloelectro/default/images/images/slides/slide4.png" alt="slide4" style="width:100%;">
		<a class="shop-now" href = "#">SHOP NOW</a>
	  </div>

	  <div class="item">
        <img src="skin/frontend/aloelectro/default/images/images/slides/slide5.png" alt="slide5" style="width:100%;">
		<a class="shop-now" href = "#">SHOP NOW</a>
	  </div>

	  <div class="item">
        <img src="skin/frontend/aloelectro/default/images/images/slides/slide6.png" alt="slide6" style="width:100%;">
		<a class="shop-now white" href = "#">SHOP NOW</a>
	  </div>

	  <div class="item">
        <img src="skin/frontend/aloelectro/default/images/images/slides/slide7.png" alt="slide7" style="width:100%;">
		<a class="shop-now" href = "#">SHOP NOW</a>
	  </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="btn-img img-left-arrow"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="btn-img img-right-arrow"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

  <div class = "center-nav-tab">
  	<ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#home">HOT</a></li>
    <li><a data-toggle="tab" href="#menu1">BEST</a></li>
    <li><a data-toggle="tab" href="#menu2">TREND</a></li>
  </ul>
  </div>
	<?php
			$storeId = Mage::app()->getStore()->getId();
			$products = Mage::getResourceModel('reports/product_collection')
			->addOrderedQty()
			->addAttributeToSelect('id')
			->addAttributeToSelect(array('name', 'price', 'small_image'))
			->setStoreId($storeId)
			->addStoreFilter($storeId)
			->setOrder('ordered_qty', 'desc');
			$_helper = $this->helper('catalog/output');
			$helpLabels = $this->helper('alothemes/labels');
	?>
  <div class="tab-content">
    <div id="home" class="tab-pane fade in active">
      <h3>HOT</h3>
    </div>
    <div id="menu1" class="tab-pane fade">
				<div class="content-products" data-margin="1" data-slider="{&quot;moveSlides&quot;:2,&quot;infiniteLoop&quot;:0,&quot;maxSlides&quot;:&quot;6&quot;,&quot;slideWidth&quot;:&quot;250&quot;,&quot;slideMargin&quot;:1,&quot;pager&quot;:1,&quot;controls&quot;:1,&quot;speed&quot;:800,&quot;auto&quot;:1,&quot;pause&quot;:6000,&quot;visibleItems&quot;:6,&quot;responsiveBreakpoints&quot;:{&quot;480&quot;:1,&quot;640&quot;:2,&quot;768&quot;:3,&quot;992&quot;:6}}" data-options="{&quot;480&quot;:&quot;1&quot;,&quot;640&quot;:&quot;2&quot;,&quot;768&quot;:&quot;3&quot;,&quot;992&quot;:&quot;6&quot;,&quot;993&quot;:&quot;6&quot;}">
	
<div class="mage-magictabs mc-latest">
                            <div class="bx-wrapper" style="max-width: 1505px;"><div class="bx-viewport" style="width: 100%; overflow: hidden; position: relative; height: 312px;"><ul class="flexisel-content products-grid latest zoomOut play" style="width: 1415%; position: relative; transition-duration: 0s; transform: translate3d(-716.5px, 0px, 0px);">
                        
                <li style="animation-delay: 0ms; float: left; list-style: none; position: relative; margin-right: 1px; width: 118.5px;" class="item item-animate">
                    <div class="per-product">
                        <div class="images-container">
                            <div class="link-view pull-left-none"> 
								<a title="Quick View" href="http://localhost:9000/magicshop/quickview/view/id/290" class="link-quickview"><i class="pe-icon pe-7s-search icons"></i>								</a>
							</div>
						   
						    <h2 class="product-name">
							   <a href="http://localhost:9000/nametest293.html" title="nametest293">nametest293</a>
						    </h2>
						     <div class="product-hover">
								                                								<a href="http://localhost:9000/nametest293.html" title="nametest293" class="product-image">
									<img class="img-responsive" src="http://localhost:9000/media/catalog/product/cache/1/small_image/250x232/9df78eab33525d08d6e5fb8d27136e95/images/catalog/product/placeholder/small_image.jpg" width="250" height="232" alt="nametest293">
									
																    </a>
							</div>
                                                         <div class="animation-box">
                                <span class="hidden">hidden</span>
                             </div>
                                <div class="actions-no hover-box">
                                    <a class="detail_links" href="http://localhost:9000/nametest293.html"></a>
                                    <div class="actions">
									    

                        
    <div class="price-box">
                                                                <span class="regular-price" id="product-price-290">
                                            <span class="price">$361.00</span>                                    </span>
                        
        </div>

																																	<div class="actions-cart">
													<button type="button" title="Add to Cart" class="button btn-cart pull-left-none" onclick="" magiccartevent="setLocation('http://localhost:9000/checkout/cart/add/uenc/aHR0cDovL2xvY2FsaG9zdDo5MDAwLw,,/product/290/form_key/rZan5WCCgm7FxDS7/')"><span><span>Add to Cart</span></span>
													</button>
												</div>
																															
										<ul class="add-to-links pull-left-none">
										  																										<li class="pull-left-none pull-compare"><span class="separator">|</span> <a href="http://localhost:9000/catalog/product_compare/add/product/290/uenc/aHR0cDovL2xvY2FsaG9zdDo5MDAwLw,,/form_key/rZan5WCCgm7FxDS7/" title="Compare" class="link-compare"><i class="icon icon-compare"></i>Compare</a></li>
																																	   																									<li class="pull-left-none pull-wishlist"><a href="http://localhost:9000/wishlist/index/add/product/290/form_key/rZan5WCCgm7FxDS7/" title="Wishlist" class="link-wishlist"><i class="icon icon-favorites"></i>Wishlist</a></li>
																																		
										</ul>
                                    </div>
                                </div>
                                                    </div>
							     				</div>
                </li>
                                        
                <li style="animation-delay: 0ms; float: left; list-style: none; position: relative; margin-right: 1px; width: 118.5px;" class="item item-animate">
                    <div class="per-product">
                        <div class="images-container">
                            <div class="link-view pull-left-none"> 
								<a title="Quick View" href="http://localhost:9000/magicshop/quickview/view/id/289" class="link-quickview"><i class="pe-icon pe-7s-search icons"></i>								</a>
							</div>
						   
						    <h2 class="product-name">
							   <a href="http://localhost:9000/nametest292.html" title="nametest292">nametest292</a>
						    </h2>
						     <div class="product-hover">
								                                								<a href="http://localhost:9000/nametest292.html" title="nametest292" class="product-image">
									<img class="img-responsive" src="http://localhost:9000/media/catalog/product/cache/1/small_image/250x232/9df78eab33525d08d6e5fb8d27136e95/images/catalog/product/placeholder/small_image.jpg" width="250" height="232" alt="nametest292">
									
																    </a>
							</div>
                                                         <div class="animation-box">
                                <span class="hidden">hidden</span>
                             </div>
                                <div class="actions-no hover-box">
                                    <a class="detail_links" href="http://localhost:9000/nametest292.html"></a>
                                    <div class="actions">
									    

                        
    <div class="price-box">
                                                                <span class="regular-price" id="product-price-289">
                                            <span class="price">$360.00</span>                                    </span>
                        
        </div>

																																	<div class="actions-cart">
													<button type="button" title="Add to Cart" class="button btn-cart pull-left-none" onclick="" magiccartevent="setLocation('http://localhost:9000/checkout/cart/add/uenc/aHR0cDovL2xvY2FsaG9zdDo5MDAwLw,,/product/289/form_key/rZan5WCCgm7FxDS7/')"><span><span>Add to Cart</span></span>
													</button>
												</div>
																															
										<ul class="add-to-links pull-left-none">
										  																										<li class="pull-left-none pull-compare"><span class="separator">|</span> <a href="http://localhost:9000/catalog/product_compare/add/product/289/uenc/aHR0cDovL2xvY2FsaG9zdDo5MDAwLw,,/form_key/rZan5WCCgm7FxDS7/" title="Compare" class="link-compare"><i class="icon icon-compare"></i>Compare</a></li>
																																	   																									<li class="pull-left-none pull-wishlist"><a href="http://localhost:9000/wishlist/index/add/product/289/form_key/rZan5WCCgm7FxDS7/" title="Wishlist" class="link-wishlist"><i class="icon icon-favorites"></i>Wishlist</a></li>
																																		
										</ul>
                                    </div>
                                </div>
                                                    </div>
							     				</div>
                </li>
                                        
                <li style="animation-delay: 0ms; float: left; list-style: none; position: relative; margin-right: 1px; width: 118.5px;" class="item item-animate">
                    <div class="per-product">
                        <div class="images-container">
                            <div class="link-view pull-left-none"> 
								<a title="Quick View" href="http://localhost:9000/magicshop/quickview/view/id/288" class="link-quickview"><i class="pe-icon pe-7s-search icons"></i>								</a>
							</div>
						   
						    <h2 class="product-name">
							   <a href="http://localhost:9000/nametest291.html" title="nametest291">nametest291</a>
						    </h2>
						     <div class="product-hover">
								                                								<a href="http://localhost:9000/nametest291.html" title="nametest291" class="product-image">
									<img class="img-responsive" src="http://localhost:9000/media/catalog/product/cache/1/small_image/250x232/9df78eab33525d08d6e5fb8d27136e95/images/catalog/product/placeholder/small_image.jpg" width="250" height="232" alt="nametest291">
									
																    </a>
							</div>
                                                         <div class="animation-box">
                                <span class="hidden">hidden</span>
                             </div>
                                <div class="actions-no hover-box">
                                    <a class="detail_links" href="http://localhost:9000/nametest291.html"></a>
                                    <div class="actions">
									    

                        
    <div class="price-box">
                                                                <span class="regular-price" id="product-price-288">
                                            <span class="price">$359.00</span>                                    </span>
                        
        </div>

																																	<div class="actions-cart">
													<button type="button" title="Add to Cart" class="button btn-cart pull-left-none" onclick="" magiccartevent="setLocation('http://localhost:9000/checkout/cart/add/uenc/aHR0cDovL2xvY2FsaG9zdDo5MDAwLw,,/product/288/form_key/rZan5WCCgm7FxDS7/')"><span><span>Add to Cart</span></span>
													</button>
												</div>
																															
										<ul class="add-to-links pull-left-none">
										  																										<li class="pull-left-none pull-compare"><span class="separator">|</span> <a href="http://localhost:9000/catalog/product_compare/add/product/288/uenc/aHR0cDovL2xvY2FsaG9zdDo5MDAwLw,,/form_key/rZan5WCCgm7FxDS7/" title="Compare" class="link-compare"><i class="icon icon-compare"></i>Compare</a></li>
																																	   																									<li class="pull-left-none pull-wishlist"><a href="http://localhost:9000/wishlist/index/add/product/288/form_key/rZan5WCCgm7FxDS7/" title="Wishlist" class="link-wishlist"><i class="icon icon-favorites"></i>Wishlist</a></li>
																																		
										</ul>
                                    </div>
                                </div>
                                                    </div>
							     				</div>
                </li>
                                        
                <li style="animation-delay: 0ms; float: left; list-style: none; position: relative; margin-right: 1px; width: 118.5px;" class="item item-animate">
                    <div class="per-product">
                        <div class="images-container">
                            <div class="link-view pull-left-none"> 
								<a title="Quick View" href="http://localhost:9000/magicshop/quickview/view/id/287" class="link-quickview"><i class="pe-icon pe-7s-search icons"></i>								</a>
							</div>
						   
						    <h2 class="product-name">
							   <a href="http://localhost:9000/nametest290.html" title="nametest290">nametest290</a>
						    </h2>
						     <div class="product-hover">
								<span class="sticker top-right"><span class="labelsale">Sale</span></span>                                								<a href="http://localhost:9000/nametest290.html" title="nametest290" class="product-image">
									<img class="img-responsive" src="http://localhost:9000/media/catalog/product/cache/1/small_image/250x232/9df78eab33525d08d6e5fb8d27136e95/images/catalog/product/placeholder/small_image.jpg" width="250" height="232" alt="nametest290">
									
																    </a>
							</div>
                                                         <div class="animation-box">
                                <span class="hidden">hidden</span>
                             </div>
                                <div class="actions-no hover-box">
                                    <a class="detail_links" href="http://localhost:9000/nametest290.html"></a>
                                    <div class="actions">
									    

                        
    <div class="price-box">
                                            
                    <p class="old-price">
                <span class="price-label">Regular Price:</span>
                <span class="price" id="old-price-287">
                    $358.00                </span>
            </p>

                            <p class="special-price">
                    <span class="price-label">Special Price</span>
                <span class="price" id="product-price-287">
                    $38.95                </span>
                </p>
                    
    
        </div>

																																	<div class="actions-cart">
													<button type="button" title="Add to Cart" class="button btn-cart pull-left-none" onclick="" magiccartevent="setLocation('http://localhost:9000/checkout/cart/add/uenc/aHR0cDovL2xvY2FsaG9zdDo5MDAwLw,,/product/287/form_key/rZan5WCCgm7FxDS7/')"><span><span>Add to Cart</span></span>
													</button>
												</div>
																															
										<ul class="add-to-links pull-left-none">
										  																										<li class="pull-left-none pull-compare"><span class="separator">|</span> <a href="http://localhost:9000/catalog/product_compare/add/product/287/uenc/aHR0cDovL2xvY2FsaG9zdDo5MDAwLw,,/form_key/rZan5WCCgm7FxDS7/" title="Compare" class="link-compare"><i class="icon icon-compare"></i>Compare</a></li>
																																	   																									<li class="pull-left-none pull-wishlist"><a href="http://localhost:9000/wishlist/index/add/product/287/form_key/rZan5WCCgm7FxDS7/" title="Wishlist" class="link-wishlist"><i class="icon icon-favorites"></i>Wishlist</a></li>
																																		
										</ul>
                                    </div>
                                </div>
                                                    </div>
							     				</div>
                </li>
                                        
                <li style="animation-delay: 0ms; float: left; list-style: none; position: relative; margin-right: 1px; width: 118.5px;" class="item item-animate">
                    <div class="per-product">
                        <div class="images-container">
                            <div class="link-view pull-left-none"> 
								<a title="Quick View" href="http://localhost:9000/magicshop/quickview/view/id/286" class="link-quickview"><i class="pe-icon pe-7s-search icons"></i>								</a>
							</div>
						   
						    <h2 class="product-name">
							   <a href="http://localhost:9000/nametest289.html" title="nametest289">nametest289</a>
						    </h2>
						     <div class="product-hover">
								                                								<a href="http://localhost:9000/nametest289.html" title="nametest289" class="product-image">
									<img class="img-responsive" src="http://localhost:9000/media/catalog/product/cache/1/small_image/250x232/9df78eab33525d08d6e5fb8d27136e95/images/catalog/product/placeholder/small_image.jpg" width="250" height="232" alt="nametest289">
									
																    </a>
							</div>
                                                         <div class="animation-box">
                                <span class="hidden">hidden</span>
                             </div>
                                <div class="actions-no hover-box">
                                    <a class="detail_links" href="http://localhost:9000/nametest289.html"></a>
                                    <div class="actions">
									    

                        
    <div class="price-box">
                                                                <span class="regular-price" id="product-price-286">
                                            <span class="price">$357.00</span>                                    </span>
                        
        </div>

																																	<div class="actions-cart">
													<button type="button" title="Add to Cart" class="button btn-cart pull-left-none" onclick="" magiccartevent="setLocation('http://localhost:9000/checkout/cart/add/uenc/aHR0cDovL2xvY2FsaG9zdDo5MDAwLw,,/product/286/form_key/rZan5WCCgm7FxDS7/')"><span><span>Add to Cart</span></span>
													</button>
												</div>
																															
										<ul class="add-to-links pull-left-none">
										  																										<li class="pull-left-none pull-compare"><span class="separator">|</span> <a href="http://localhost:9000/catalog/product_compare/add/product/286/uenc/aHR0cDovL2xvY2FsaG9zdDo5MDAwLw,,/form_key/rZan5WCCgm7FxDS7/" title="Compare" class="link-compare"><i class="icon icon-compare"></i>Compare</a></li>
																																	   																									<li class="pull-left-none pull-wishlist"><a href="http://localhost:9000/wishlist/index/add/product/286/form_key/rZan5WCCgm7FxDS7/" title="Wishlist" class="link-wishlist"><i class="icon icon-favorites"></i>Wishlist</a></li>
																																		
										</ul>
                                    </div>
                                </div>
                                                    </div>
							     				</div>
                </li>
                                        
                <li style="animation-delay: 0ms; float: left; list-style: none; position: relative; margin-right: 1px; width: 118.5px;" class="item item-animate">
                    <div class="per-product">
                        <div class="images-container">
                            <div class="link-view pull-left-none"> 
								<a title="Quick View" href="http://localhost:9000/magicshop/quickview/view/id/285" class="link-quickview"><i class="pe-icon pe-7s-search icons"></i>								</a>
							</div>
						   
						    <h2 class="product-name">
							   <a href="http://localhost:9000/nametest288.html" title="nametest288">nametest288</a>
						    </h2>
						     <div class="product-hover">
								                                								<a href="http://localhost:9000/nametest288.html" title="nametest288" class="product-image">
									<img class="img-responsive" src="http://localhost:9000/media/catalog/product/cache/1/small_image/250x232/9df78eab33525d08d6e5fb8d27136e95/images/catalog/product/placeholder/small_image.jpg" width="250" height="232" alt="nametest288">
									
																    </a>
							</div>
                                                         <div class="animation-box">
                                <span class="hidden">hidden</span>
                             </div>
                                <div class="actions-no hover-box">
                                    <a class="detail_links" href="http://localhost:9000/nametest288.html"></a>
                                    <div class="actions">
									    

                        
    <div class="price-box">
                                                                <span class="regular-price" id="product-price-285">
                                            <span class="price">$356.00</span>                                    </span>
                        
        </div>

																																	<div class="actions-cart">
													<button type="button" title="Add to Cart" class="button btn-cart pull-left-none" onclick="" magiccartevent="setLocation('http://localhost:9000/checkout/cart/add/uenc/aHR0cDovL2xvY2FsaG9zdDo5MDAwLw,,/product/285/form_key/rZan5WCCgm7FxDS7/')"><span><span>Add to Cart</span></span>
													</button>
												</div>
																															
										<ul class="add-to-links pull-left-none">
										  																										<li class="pull-left-none pull-compare"><span class="separator">|</span> <a href="http://localhost:9000/catalog/product_compare/add/product/285/uenc/aHR0cDovL2xvY2FsaG9zdDo5MDAwLw,,/form_key/rZan5WCCgm7FxDS7/" title="Compare" class="link-compare"><i class="icon icon-compare"></i>Compare</a></li>
																																	   																									<li class="pull-left-none pull-wishlist"><a href="http://localhost:9000/wishlist/index/add/product/285/form_key/rZan5WCCgm7FxDS7/" title="Wishlist" class="link-wishlist"><i class="icon icon-favorites"></i>Wishlist</a></li>
																																		
										</ul>
                                    </div>
                                </div>
                                                    </div>
							     				</div>
                </li>
                                        
                <li style="animation-delay: 0ms; float: left; list-style: none; position: relative; margin-right: 1px; width: 118.5px;" class="item item-animate">
                    <div class="per-product">
                        <div class="images-container">
                            <div class="link-view pull-left-none"> 
								<a title="Quick View" href="http://localhost:9000/magicshop/quickview/view/id/284" class="link-quickview"><i class="pe-icon pe-7s-search icons"></i>								</a>
							</div>
						   
						    <h2 class="product-name">
							   <a href="http://localhost:9000/nametest287.html" title="nametest287">nametest287</a>
						    </h2>
						     <div class="product-hover">
								                                								<a href="http://localhost:9000/nametest287.html" title="nametest287" class="product-image">
									<img class="img-responsive" src="http://localhost:9000/media/catalog/product/cache/1/small_image/250x232/9df78eab33525d08d6e5fb8d27136e95/images/catalog/product/placeholder/small_image.jpg" width="250" height="232" alt="nametest287">
									
																    </a>
							</div>
                                                         <div class="animation-box">
                                <span class="hidden">hidden</span>
                             </div>
                                <div class="actions-no hover-box">
                                    <a class="detail_links" href="http://localhost:9000/nametest287.html"></a>
                                    <div class="actions">
									    

                        
    <div class="price-box">
                                                                <span class="regular-price" id="product-price-284">
                                            <span class="price">$355.00</span>                                    </span>
                        
        </div>

																																	<div class="actions-cart">
													<button type="button" title="Add to Cart" class="button btn-cart pull-left-none" onclick="" magiccartevent="setLocation('http://localhost:9000/checkout/cart/add/uenc/aHR0cDovL2xvY2FsaG9zdDo5MDAwLw,,/product/284/form_key/rZan5WCCgm7FxDS7/')"><span><span>Add to Cart</span></span>
													</button>
												</div>
																															
										<ul class="add-to-links pull-left-none">
										  																										<li class="pull-left-none pull-compare"><span class="separator">|</span> <a href="http://localhost:9000/catalog/product_compare/add/product/284/uenc/aHR0cDovL2xvY2FsaG9zdDo5MDAwLw,,/form_key/rZan5WCCgm7FxDS7/" title="Compare" class="link-compare"><i class="icon icon-compare"></i>Compare</a></li>
																																	   																									<li class="pull-left-none pull-wishlist"><a href="http://localhost:9000/wishlist/index/add/product/284/form_key/rZan5WCCgm7FxDS7/" title="Wishlist" class="link-wishlist"><i class="icon icon-favorites"></i>Wishlist</a></li>
																																		
										</ul>
                                    </div>
                                </div>
                                                    </div>
							     				</div>
                </li>
                                        
                <li style="animation-delay: 0ms; float: left; list-style: none; position: relative; margin-right: 1px; width: 118.5px;" class="item item-animate">
                    <div class="per-product">
                        <div class="images-container">
                            <div class="link-view pull-left-none"> 
								<a title="Quick View" href="http://localhost:9000/magicshop/quickview/view/id/283" class="link-quickview"><i class="pe-icon pe-7s-search icons"></i>								</a>
							</div>
						   
						    <h2 class="product-name">
							   <a href="http://localhost:9000/nametest286.html" title="nametest286">nametest286</a>
						    </h2>
						     <div class="product-hover">
								                                								<a href="http://localhost:9000/nametest286.html" title="nametest286" class="product-image">
									<img class="img-responsive" src="http://localhost:9000/media/catalog/product/cache/1/small_image/250x232/9df78eab33525d08d6e5fb8d27136e95/images/catalog/product/placeholder/small_image.jpg" width="250" height="232" alt="nametest286">
									
																    </a>
							</div>
                                                         <div class="animation-box">
                                <span class="hidden">hidden</span>
                             </div>
                                <div class="actions-no hover-box">
                                    <a class="detail_links" href="http://localhost:9000/nametest286.html"></a>
                                    <div class="actions">
									    

                        
    <div class="price-box">
                                                                <span class="regular-price" id="product-price-283">
                                            <span class="price">$354.00</span>                                    </span>
                        
        </div>

																																	<div class="actions-cart">
													<button type="button" title="Add to Cart" class="button btn-cart pull-left-none" onclick="" magiccartevent="setLocation('http://localhost:9000/checkout/cart/add/uenc/aHR0cDovL2xvY2FsaG9zdDo5MDAwLw,,/product/283/form_key/rZan5WCCgm7FxDS7/')"><span><span>Add to Cart</span></span>
													</button>
												</div>
																															
										<ul class="add-to-links pull-left-none">
										  																										<li class="pull-left-none pull-compare"><span class="separator">|</span> <a href="http://localhost:9000/catalog/product_compare/add/product/283/uenc/aHR0cDovL2xvY2FsaG9zdDo5MDAwLw,,/form_key/rZan5WCCgm7FxDS7/" title="Compare" class="link-compare"><i class="icon icon-compare"></i>Compare</a></li>
																																	   																									<li class="pull-left-none pull-wishlist"><a href="http://localhost:9000/wishlist/index/add/product/283/form_key/rZan5WCCgm7FxDS7/" title="Wishlist" class="link-wishlist"><i class="icon icon-favorites"></i>Wishlist</a></li>
																																		
										</ul>
                                    </div>
                                </div>
                                                    </div>
							     				</div>
                </li>
                                        
                <li style="animation-delay: 0ms; float: left; list-style: none; position: relative; margin-right: 1px; width: 118.5px;" class="item item-animate">
                    <div class="per-product">
                        <div class="images-container">
                            <div class="link-view pull-left-none"> 
								<a title="Quick View" href="http://localhost:9000/magicshop/quickview/view/id/282" class="link-quickview"><i class="pe-icon pe-7s-search icons"></i>								</a>
							</div>
						   
						    <h2 class="product-name">
							   <a href="http://localhost:9000/nametest285.html" title="nametest285">nametest285</a>
						    </h2>
						     <div class="product-hover">
								                                								<a href="http://localhost:9000/nametest285.html" title="nametest285" class="product-image">
									<img class="img-responsive" src="http://localhost:9000/media/catalog/product/cache/1/small_image/250x232/9df78eab33525d08d6e5fb8d27136e95/images/catalog/product/placeholder/small_image.jpg" width="250" height="232" alt="nametest285">
									
																    </a>
							</div>
                                                         <div class="animation-box">
                                <span class="hidden">hidden</span>
                             </div>
                                <div class="actions-no hover-box">
                                    <a class="detail_links" href="http://localhost:9000/nametest285.html"></a>
                                    <div class="actions">
									    

                        
    <div class="price-box">
                                                                <span class="regular-price" id="product-price-282">
                                            <span class="price">$353.00</span>                                    </span>
                        
        </div>

																																	<div class="actions-cart">
													<button type="button" title="Add to Cart" class="button btn-cart pull-left-none" onclick="" magiccartevent="setLocation('http://localhost:9000/checkout/cart/add/uenc/aHR0cDovL2xvY2FsaG9zdDo5MDAwLw,,/product/282/form_key/rZan5WCCgm7FxDS7/')"><span><span>Add to Cart</span></span>
													</button>
												</div>
																															
										<ul class="add-to-links pull-left-none">
										  																										<li class="pull-left-none pull-compare"><span class="separator">|</span> <a href="http://localhost:9000/catalog/product_compare/add/product/282/uenc/aHR0cDovL2xvY2FsaG9zdDo5MDAwLw,,/form_key/rZan5WCCgm7FxDS7/" title="Compare" class="link-compare"><i class="icon icon-compare"></i>Compare</a></li>
																																	   																									<li class="pull-left-none pull-wishlist"><a href="http://localhost:9000/wishlist/index/add/product/282/form_key/rZan5WCCgm7FxDS7/" title="Wishlist" class="link-wishlist"><i class="icon icon-favorites"></i>Wishlist</a></li>
																																		
										</ul>
                                    </div>
                                </div>
                                                    </div>
							     				</div>
                </li>
                                        
                <li style="animation-delay: 0ms; float: left; list-style: none; position: relative; margin-right: 1px; width: 118.5px;" class="item item-animate">
                    <div class="per-product">
                        <div class="images-container">
                            <div class="link-view pull-left-none"> 
								<a title="Quick View" href="http://localhost:9000/magicshop/quickview/view/id/281" class="link-quickview"><i class="pe-icon pe-7s-search icons"></i>								</a>
							</div>
						   
						    <h2 class="product-name">
							   <a href="http://localhost:9000/nametest284.html" title="nametest284">nametest284</a>
						    </h2>
						     <div class="product-hover">
								                                								<a href="http://localhost:9000/nametest284.html" title="nametest284" class="product-image">
									<img class="img-responsive" src="http://localhost:9000/media/catalog/product/cache/1/small_image/250x232/9df78eab33525d08d6e5fb8d27136e95/images/catalog/product/placeholder/small_image.jpg" width="250" height="232" alt="nametest284">
									
																    </a>
							</div>
                                                         <div class="animation-box">
                                <span class="hidden">hidden</span>
                             </div>
                                <div class="actions-no hover-box">
                                    <a class="detail_links" href="http://localhost:9000/nametest284.html"></a>
                                    <div class="actions">
									    

                        
    <div class="price-box">
                                                                <span class="regular-price" id="product-price-281">
                                            <span class="price">$352.00</span>                                    </span>
                        
        </div>

																																	<div class="actions-cart">
													<button type="button" title="Add to Cart" class="button btn-cart pull-left-none" onclick="" magiccartevent="setLocation('http://localhost:9000/checkout/cart/add/uenc/aHR0cDovL2xvY2FsaG9zdDo5MDAwLw,,/product/281/form_key/rZan5WCCgm7FxDS7/')"><span><span>Add to Cart</span></span>
													</button>
												</div>
																															
										<ul class="add-to-links pull-left-none">
										  																										<li class="pull-left-none pull-compare"><span class="separator">|</span> <a href="http://localhost:9000/catalog/product_compare/add/product/281/uenc/aHR0cDovL2xvY2FsaG9zdDo5MDAwLw,,/form_key/rZan5WCCgm7FxDS7/" title="Compare" class="link-compare"><i class="icon icon-compare"></i>Compare</a></li>
																																	   																									<li class="pull-left-none pull-wishlist"><a href="http://localhost:9000/wishlist/index/add/product/281/form_key/rZan5WCCgm7FxDS7/" title="Wishlist" class="link-wishlist"><i class="icon icon-favorites"></i>Wishlist</a></li>
																																		
										</ul>
                                    </div>
                                </div>
                                                    </div>
							     				</div>
                </li>
                                        
                <li style="animation-delay: 0ms; float: left; list-style: none; position: relative; margin-right: 1px; width: 118.5px;" class="item item-animate">
                    <div class="per-product">
                        <div class="images-container">
                            <div class="link-view pull-left-none"> 
								<a title="Quick View" href="http://localhost:9000/magicshop/quickview/view/id/280" class="link-quickview"><i class="pe-icon pe-7s-search icons"></i>								</a>
							</div>
						   
						    <h2 class="product-name">
							   <a href="http://localhost:9000/nametest283.html" title="nametest283">nametest283</a>
						    </h2>
						     <div class="product-hover">
								                                								<a href="http://localhost:9000/nametest283.html" title="nametest283" class="product-image">
									<img class="img-responsive" src="http://localhost:9000/media/catalog/product/cache/1/small_image/250x232/9df78eab33525d08d6e5fb8d27136e95/images/catalog/product/placeholder/small_image.jpg" width="250" height="232" alt="nametest283">
									
																    </a>
							</div>
                                                         <div class="animation-box">
                                <span class="hidden">hidden</span>
                             </div>
                                <div class="actions-no hover-box">
                                    <a class="detail_links" href="http://localhost:9000/nametest283.html"></a>
                                    <div class="actions">
									    

                        
    <div class="price-box">
                                                                <span class="regular-price" id="product-price-280">
                                            <span class="price">$351.00</span>                                    </span>
                        
        </div>

																																	<div class="actions-cart">
													<button type="button" title="Add to Cart" class="button btn-cart pull-left-none" onclick="" magiccartevent="setLocation('http://localhost:9000/checkout/cart/add/uenc/aHR0cDovL2xvY2FsaG9zdDo5MDAwLw,,/product/280/form_key/rZan5WCCgm7FxDS7/')"><span><span>Add to Cart</span></span>
													</button>
												</div>
																															
										<ul class="add-to-links pull-left-none">
										  																										<li class="pull-left-none pull-compare"><span class="separator">|</span> <a href="http://localhost:9000/catalog/product_compare/add/product/280/uenc/aHR0cDovL2xvY2FsaG9zdDo5MDAwLw,,/form_key/rZan5WCCgm7FxDS7/" title="Compare" class="link-compare"><i class="icon icon-compare"></i>Compare</a></li>
																																	   																									<li class="pull-left-none pull-wishlist"><a href="http://localhost:9000/wishlist/index/add/product/280/form_key/rZan5WCCgm7FxDS7/" title="Wishlist" class="link-wishlist"><i class="icon icon-favorites"></i>Wishlist</a></li>
																																		
										</ul>
                                    </div>
                                </div>
                                                    </div>
							     				</div>
                </li>
                                        
                <li style="animation-delay: 0ms; float: left; list-style: none; position: relative; margin-right: 1px; width: 118.5px;" class="item item-animate">
                    <div class="per-product">
                        <div class="images-container">
                            <div class="link-view pull-left-none"> 
								<a title="Quick View" href="http://localhost:9000/magicshop/quickview/view/id/279" class="link-quickview"><i class="pe-icon pe-7s-search icons"></i>								</a>
							</div>
						   
						    <h2 class="product-name">
							   <a href="http://localhost:9000/nametest282.html" title="nametest282">nametest282</a>
						    </h2>
						     <div class="product-hover">
								                                								<a href="http://localhost:9000/nametest282.html" title="nametest282" class="product-image">
									<img class="img-responsive" src="http://localhost:9000/media/catalog/product/cache/1/small_image/250x232/9df78eab33525d08d6e5fb8d27136e95/images/catalog/product/placeholder/small_image.jpg" width="250" height="232" alt="nametest282">
									
																    </a>
							</div>
                                                         <div class="animation-box">
                                <span class="hidden">hidden</span>
                             </div>
                                <div class="actions-no hover-box">
                                    <a class="detail_links" href="http://localhost:9000/nametest282.html"></a>
                                    <div class="actions">
									    

                        
    <div class="price-box">
                                                                <span class="regular-price" id="product-price-279">
                                            <span class="price">$350.00</span>                                    </span>
                        
        </div>

																																	<div class="actions-cart">
													<button type="button" title="Add to Cart" class="button btn-cart pull-left-none" onclick="" magiccartevent="setLocation('http://localhost:9000/checkout/cart/add/uenc/aHR0cDovL2xvY2FsaG9zdDo5MDAwLw,,/product/279/form_key/rZan5WCCgm7FxDS7/')"><span><span>Add to Cart</span></span>
													</button>
												</div>
																															
										<ul class="add-to-links pull-left-none">
										  																										<li class="pull-left-none pull-compare"><span class="separator">|</span> <a href="http://localhost:9000/catalog/product_compare/add/product/279/uenc/aHR0cDovL2xvY2FsaG9zdDo5MDAwLw,,/form_key/rZan5WCCgm7FxDS7/" title="Compare" class="link-compare"><i class="icon icon-compare"></i>Compare</a></li>
																																	   																									<li class="pull-left-none pull-wishlist"><a href="http://localhost:9000/wishlist/index/add/product/279/form_key/rZan5WCCgm7FxDS7/" title="Wishlist" class="link-wishlist"><i class="icon icon-favorites"></i>Wishlist</a></li>
																																		
										</ul>
                                    </div>
                                </div>
                                                    </div>
							     				</div>
                </li>
                        </ul></div><div class="bx-controls bx-has-pager bx-has-controls-direction"><div class="bx-pager bx-default-pager"><div class="bx-pager-item"><a href="" data-slide-index="0" class="bx-pager-link">1</a></div><div class="bx-pager-item"><a href="" data-slide-index="1" class="bx-pager-link">2</a></div><div class="bx-pager-item"><a href="" data-slide-index="2" class="bx-pager-link">3</a></div><div class="bx-pager-item"><a href="" data-slide-index="3" class="bx-pager-link">4</a></div><div class="bx-pager-item"><a href="" data-slide-index="4" class="bx-pager-link active">5</a></div></div><div class="bx-controls-direction"><a class="bx-prev" href=""><i class="fa fa-angle-left"></i></a><a class="bx-next" href=""><i class="fa fa-angle-right"></i></a></div></div></div>
</div>


	</div>
    </div>
			
    </div>
    <div id="menu2" class="tab-pane fade">
      <h3>TREND</h3>
      
    </div>
  </div>
</div>

<script type="text/javascript">
	jQuery(document).ready(function($){
		$('#<?php echo $idHtml ?>').bxSlider({
			auto: true,
			captions: true,
			<?php echo $this->getBxslider() ?>
			onSlideBefore: function(el) {
				el.siblings().find('.bx-caption').removeClass('play');
				el.find('.bx-caption').addClass('play').addClass('start');				
			},
		});
	});
</script>

