<?php
/**
 * Magiccart 
 * @category  Magiccart 
 * @copyright   Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license   http://www.magiccart.net/license-agreement.html
 * @Author: Magiccart<team.magiccart@gmail.com>
 * @@Create Date: 2014-09-10 10:21:05
 * @@Modify Date: 2016-06-14 15:04:17
 * @@Function:
 */
?>
<!--
<?php 	
if(! Mage::getStoreConfig('magicslider/general/enabled')) return;
$bannerCollection = $this->_getCollection();
if(($bannerCollection->count())<=0) return;
$imageCollection = $this->_getMagicsliderImageCollection($bannerCollection); 		
$width  = $this->getData('width');
$height = $this->getData('height');
$idHtml = $this->generateRandomString();
?>
<?php foreach ($imageCollection as $item) : ?>
	<?php 
		$content = $item['content']; 		
		$images = $this->getSortedImages($content);
	?>
	<?php if(isset($images) && !empty($images) && count($images)>0) : ?>
		<div class="magicslider">
			<div id="<?php echo $idHtml ?>">
			<?php $start = 'play start' ?>
			<?php foreach($images as $image): ?>
				<div class="item">
					<a  href="<?php echo ( isset($image['link']) && $image['link'] ) ? ($image['link']) : '#'; ?>">
						<img src="<?php echo $this->helper('magicslider')->resizeImg($image['file'], $width, $height);?>" alt="<?php echo $image['label'] ? $image['label'] : 'magicslider' ?>">
					</a>
					<?php if(isset($image['html']) && $image['html']) : ?>
						<div class="bx-caption <?php echo $start ?>">
							<?php echo $image['html'] ?>
						</div>
					<?php endif ?>
				</div>
				<?php $start = '' ?>
			<?php endforeach;?>
			</div>
		</div>

	<?php endif;?>
<?php endforeach;?>-->
<link rel="stylesheet" type="text/css" href="/skin/slick/slick.css"/>
<link rel="stylesheet" type="text/css" href="/skin/slick/slick-theme.css"/>
<script type="text/javascript" src="/skin/slick/slick.min.js"></script>
<style>
	.btn-img {
    width: 25px;
    height: 45px;
    display: inline-block;
    background-repeat: no-repeat;    
    background-position: center;
    background-color: transparent;    
    vertical-align: middle;
}

.img-small{
	width: 12px;
    height: 24px;
}

.img-right-arrow {
    background-image: url(skin/frontend/aloelectro/default/images/images/right_arrow.png);
    background-size: 100% 100%;
	position: absolute;
	top: 40%;
}

.img-left-arrow {
    background-image: url(skin/frontend/aloelectro/default/images/images/left_arrow.png);
    background-size: 100% 100%;
	position: absolute;
	top: 40%;
	left: 30%;
}

.carousel-control.right, .carousel-control.left{
	background-image: none;
}

.carousel-indicators{
	z-index: 1;
}

.carousel-indicators li{
	background-color: #fff;
}

.carousel-indicators .active{
	background-color: #FF2A00;
	border-color: #FF2A00;
}

.carousel-inner .item img{
	height: 300px;
}

.shop-now{
	position: absolute;
    top: 75%;
    left: 25.5%;
    padding: 4px 25px;
    color: white;
    background-color: #FF2A00;
    border-radius: 8px;
    font-size: 12px;
    font-weight: bold;
}

.shop-now.white{
	color: black;
    background-color: #fff;
}

.shop-now:hover{
	color: white;
}

.shop-now.white:hover{
	color: black;
}

.center-nav-tab{
	text-align:center;
	margin-top:5px;
}

.center-nav-tab .nav.nav-tabs{
	display: inline-block;
    border: none;
}

.center-nav-tab .nav-tabs>li>a{
	padding: 4px 24px;
	font-size: 18px;
	font-weight: bold;
}

.center-nav-tab .nav-tabs>li.active>a:before, 
.center-nav-tab .nav-tabs>li.active>a:hover:before, 
.center-nav-tab .nav-tabs>li.active>a:focus:before 
{
    content: '';
    display: block;
    width: 0px;
    height: 0;
    position: absolute;
    border-left: 5px solid transparent;
    border-right: 5px solid transparent;
    border-top: 5px solid #FF2A00;
    left: 43%;
    bottom: -18%;
}

.center-nav-tab .nav-tabs>li.active>a, 
.center-nav-tab .nav-tabs>li.active>a:hover, 
.center-nav-tab .nav-tabs>li.active>a:focus {
    color: #fff;
    cursor: default;
    background-color: #FF2A00;
    border: 1px solid #FF2A00;
    border-bottom-color: none;
	border-radius: 0;
}

@media screen and (min-width: 768px){
	.carousel-indicators {
		bottom: 0px;
	}
}

.custom-product-carousel .carousel-control     		 { width:  4%; }
.custom-product-carousel .carousel-control.left,.carousel-control.right {margin-left:15px;background-image:none;}
@media (max-width: 767px) {
	.custom-product-carousel.carousel-inner .active.left { left: -100%; }
	.custom-product-carousel.carousel-inner .next        { left:  100%; }
	.custom-product-carousel .carousel-inner .prev		 { left: -100%; }
	.custom-product-carousel.active > div { display:none; }
	.custom-product-carousel .active > div:first-child { display:block; }

}
@media (min-width: 767px) and (max-width: 992px ) {
	.custom-product-carousel .carousel-inner .active.left { left: -50%; }
	.custom-product-carousel.carousel-inner .next        { left:  50%; }
	.custom-product-carousel .carousel-inner .prev		 { left: -50%; }
	.custom-product-carousel .active > div { display:none; }
	.custom-product-carousel .active > div:first-child { display:block; }
	.custom-product-carousel .active > div:first-child + div { display:block; }
}
@media (min-width: 992px ) {
	.custom-product-carousel .carousel-inner .active.left { left: -16.7%; }
	.custom-product-carousel .carousel-inner .next        { left:  16.7%; }
	.custom-product-carousel .carousel-inner .prev		 { left: -16.7%; }	
}

.carousel-inner .img-product.img-circle{
	border: 1px solid #dedede;
	height: 9vw;
}

.carousel-inner .product-name{
	font-size: 12px;
    font-weight: bold;
    color: black;
}

@import url(http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css);
.col-item
{
    border: 1px solid #E1E1E1;
    border-radius: 5px;
    background: #FFF;
}
.col-item .photo img
{
    margin: 0 auto;
    width: 100%;
}

.col-item .info
{
    padding: 10px;
    border-radius: 0 0 5px 5px;
    margin-top: 1px;
}

.col-item:hover .info {
    background-color: #F5F5DC;
}
.col-item .price
{
    /*width: 50%;*/
    float: left;
    margin-top: 5px;
}

.col-item .price h5
{
    line-height: 20px;
    margin: 0;
}

.price-text-color
{
    color: #219FD1;
}

.col-item .info .rating
{
    color: #777;
}

.col-item .rating
{
    /*width: 50%;*/
    float: left;
    font-size: 17px;
    text-align: right;
    line-height: 52px;
    margin-bottom: 10px;
    height: 52px;
}

.col-item .separator
{
    border-top: 1px solid #E1E1E1;
}

.clear-left
{
    clear: left;
}

.col-item .separator p
{
    line-height: 20px;
    margin-bottom: 0;
    margin-top: 10px;
    text-align: center;
}

.col-item .separator p i
{
    margin-right: 5px;
}
.col-item .btn-add
{
    width: 50%;
    float: left;
}

.col-item .btn-add
{
    border-right: 1px solid #E1E1E1;
}

.col-item .btn-details
{
    width: 50%;
    float: left;
    padding-left: 10px;
}
.controls
{
    margin-top: 20px;
}
[data-slide="prev"]
{
    margin-right: 10px;
}

.new-product-section{

}
</style>

<div class="container">
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
	  <li data-target="#myCarousel" data-slide-to="3"></li>
      <li data-target="#myCarousel" data-slide-to="4"></li>
      <li data-target="#myCarousel" data-slide-to="5"></li>
	  <li data-target="#myCarousel" data-slide-to="6"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <img src="skin/frontend/aloelectro/default/images/images/slides/slide1.png" alt="slide1" style="width:100%;">
		<a class="shop-now" href = "#">SHOP NOW</a>
      </div>
      <div class="item">
        <img src="skin/frontend/aloelectro/default/images/images/slides/slide2.png" alt="slide2" style="width:100%;">
		<a class="shop-now" href = "#">SHOP NOW</a>
	  </div>
    
      <div class="item">
        <img src="skin/frontend/aloelectro/default/images/images/slides/slide3.png" alt="slide3" style="width:100%;">
		<a class="shop-now" href = "#">SHOP NOW</a>
	  </div>

	  <div class="item">
        <img src="skin/frontend/aloelectro/default/images/images/slides/slide4.png" alt="slide4" style="width:100%;">
		<a class="shop-now" href = "#">SHOP NOW</a>
	  </div>

	  <div class="item">
        <img src="skin/frontend/aloelectro/default/images/images/slides/slide5.png" alt="slide5" style="width:100%;">
		<a class="shop-now" href = "#">SHOP NOW</a>
	  </div>

	  <div class="item">
        <img src="skin/frontend/aloelectro/default/images/images/slides/slide6.png" alt="slide6" style="width:100%;">
		<a class="shop-now white" href = "#">SHOP NOW</a>
	  </div>

	  <div class="item">
        <img src="skin/frontend/aloelectro/default/images/images/slides/slide7.png" alt="slide7" style="width:100%;">
		<a class="shop-now" href = "#">SHOP NOW</a>
	  </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="btn-img img-left-arrow"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="btn-img img-right-arrow"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

  <div class = "center-nav-tab">
  	<ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#home">HOT</a></li>
    <li><a data-toggle="tab" href="#menu1">BEST</a></li>
    <li><a data-toggle="tab" href="#menu2">TREND</a></li>
  </ul>
  </div>
	<?php
			$storeId = Mage::app()->getStore()->getId();
			$products_best = Mage::getResourceModel('reports/product_collection')
			->addOrderedQty()
			->addAttributeToSelect('id')
			->addAttributeToSelect(array('name', 'price', 'small_image'))
			->setStoreId($storeId)
			->addStoreFilter($storeId)
			->setOrder('ordered_qty', 'desc');

			 $products_hot = Mage::getResourceModel('reports/product_collection')
			->addStoreFilter($store_id)
			->addAttributeToFilter('visibility', 4)
			->addAttributeToFilter('status', 1)  
			->addAttributeToSelect('*')
			->setVisibility(array(2,3,4))                          
			->setOrder('created_at', 'desc');

			$_helper = $this->helper('catalog/output');
			$helpLabels = $this->helper('alothemes/labels');
	?>
  <div class="tab-content">
    <div id="home" class="tab-pane fade in active">
		<div class="col-md-10 col-md-offset-1">
		<div class="carousel slide custom-product-carousel" data-ride="carousel" data-type="multi" data-interval="3000" id="myCarousel1">
		<div class="carousel-inner">
			<?php $i=0; foreach ($products_hot as $_product): ?>
			<div class="item <?php if($i == 0) echo 'active'?>">
			<div class="col-md-2 col-sm-6 col-xs-12">
				<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
					<img class="img-responsive img-circle img-product" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($width , $height); ?>" width="<?php echo $width ?>" height="<?php echo $height ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
				</a>
				<div class="text-center product-name">
					<?php  echo $_product->getName() ?>
				</div>
			</div>
			</div>
			<?php $i++;?>
			<?php endforeach ?>
		</div>
		<a class="left carousel-control" style="margin-left:-5%" href="#myCarousel1" data-slide="prev"><i class="btn-img img-left-arrow img-small"></i></a>
		<a class="right carousel-control" style="margin-right:-4%" href="#myCarousel1" data-slide="next"><i class="btn-img img-right-arrow img-small"></i></a>
		</div>
		</div>
	</div>
    <div id="menu1" class="tab-pane fade">
		<div class="col-md-10 col-md-offset-1">
		<div class="carousel slide custom-product-carousel" data-ride="carousel" data-type="multi" data-interval="3000" id="myCarousel2">
		<div class="carousel-inner">
			<?php $i=0; foreach ($products_best as $_product): ?>
			<div class="item <?php if($i == 0) echo 'active'?>">
			<div class="col-md-2 col-sm-6 col-xs-12">
				<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
					<img class="img-responsive img-circle img-product" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($width , $height); ?>" width="<?php echo $width ?>" height="<?php echo $height ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
				</a>
				<div class="text-center product-name">
					<?php  echo $_product->getName() ?>
				</div>
			</div>
			</div>
			<?php $i++;?>
			<?php endforeach ?>
		</div>
		<a class="left carousel-control" style="margin-left:-5%" href="#myCarousel2" data-slide="prev"><i class="btn-img img-left-arrow img-small"></i></a>
		<a class="right carousel-control" style="margin-right:-4%" href="#myCarousel2" data-slide="next"><i class="btn-img img-right-arrow img-small"></i></a>
		</div>
		</div>
    </div>
    <div id="menu2" class="tab-pane fade">
      <div class="col-md-10 col-md-offset-1">
		<div class="carousel slide custom-product-carousel" data-ride="carousel" data-type="multi" data-interval="3000" id="myCarousel3">
		<div class="carousel-inner">
			<?php $i=0; foreach ($products_best as $_product): ?>
			<div class="item <?php if($i == 0) echo 'active'?>">
			<div class="col-md-2 col-sm-6 col-xs-12">
				<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
					<img class="img-responsive img-circle img-product" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($width , $height); ?>" width="<?php echo $width ?>" height="<?php echo $height ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
				</a>
				<div class="text-center product-name">
					<?php  echo $_product->getName() ?>
				</div>
			</div>
			</div>
			<?php $i++;?>
			<?php endforeach ?>
		</div>
		<a class="left carousel-control" style="margin-left:-5%" href="#myCarousel3" data-slide="prev"><i class="btn-img img-left-arrow img-small"></i></a>
		<a class="right carousel-control" style="margin-right:-4%" href="#myCarousel3" data-slide="next"><i class="btn-img img-right-arrow img-small"></i></a>
		</div>
		</div>
    </div>
  </div>
  <div class="row new-product-section">
            <div class="col-md-9">
                <h1 style="margin-top: 20px; color:black;"><strong style="font-size: 20px;">New Product</strong></h1>
            </div>
            <div class="col-md-3">
                <!-- Controls -->
                <div class="controls pull-right hidden-xs">
                    <a class="left fa fa-chevron-left btn btn-success" href="#carousel-example"
                        data-slide="prev"></a><a class="right fa fa-chevron-right btn btn-success" href="#carousel-example"
                            data-slide="next"></a>
                </div>
            </div>
        </div>
        <div id="carousel-example" class="carousel slide hidden-xs" data-ride="carousel">
            <!-- Wrapper for slides -->
			
			<?php $index = 0; ?>
            <div class="carousel-inner">
				<?php foreach ($products_hot as $_product): ?>
					<?php if($index % 4 == 0): ?>
						<div class="item <?php if($index == 0) echo 'active'?>">
							<div class="row">
					<?php endif; ?>
					
								<div class="col-sm-3">
									<div class="col-item">
										<div class="photo">
											<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
												<img class="img-responsive" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($width , $height); ?>" width="<?php echo $width ?>" height="<?php echo $height ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
											</a>
										</div>
										<div class="info">
											<div class="row">
												<div class="price col-md-6">
													<h5><?php echo $_product->getName(); ?></h5>
													<h5 class="price-text-color">$199.99 </h5>
												</div>
												<div class="rating hidden-sm col-md-6">
													<i class="price-text-color fa fa-star"></i>
													<i class="price-text-color fa fa-star"></i>
													<i class="price-text-color fa fa-star"></i>
													<i class="price-text-color fa fa-star"></i>
													<i class="fa fa-star"></i>
												</div>
											</div>
											<div class="clearfix">
											</div>
										</div>
									</div>
								</div>

					<?php if(($index + 1) % 4 == 0 || ($index + 1) == count($products_hot)): ?>
							</div>
						</div>
					<?php endif; ?>
					<?php $index += 1; ?>
				<?php endforeach?>
            </div>
        </div>
</div>

<script type="text/javascript">
	jQuery(document).ready(function($){
		$('#<?php echo $idHtml ?>').bxSlider({
			auto: true,
			captions: true,
			<?php echo $this->getBxslider() ?>
			onSlideBefore: function(el) {
				el.siblings().find('.bx-caption').removeClass('play');
				el.find('.bx-caption').addClass('play').addClass('start');				
			},
		});

		$('.carousel[data-type="multi"] .item').each(function(){
			var next = $(this).next();
			if (!next.length) {
				next = $(this).siblings(':first');
			}
			next.children(':first-child').clone().appendTo($(this));
			
			for (var i=0;i<4;i++) {
				next=next.next();
				if (!next.length) {
					next = $(this).siblings(':first');
				}
				
				next.children(':first-child').clone().appendTo($(this));
			}
		});
	});
</script>

