<link href="<?php echo $this->getSkinUrl('geoipdefaultlanguage/style.css') ?>" rel="stylesheet" type="text/css" />
<script src="<?php echo $this->getSkinUrl('geoipdefaultlanguage/js/jquery-1.7.1.js') ?>" type="text/javascript"></script>
<script src="<?php echo $this->getSkinUrl('geoipdefaultlanguage/js/resposive_popup.js') ?>" type="text/javascript"></script>
<?php
$allowedCurrencies = Mage::app()->getStore()->getAvailableCurrencyCodes(true);
$_helper = Mage::helper('geoipdefaultlanguage');
$storeId = Mage::app()->getStore()->getId();
$currencyCode = Mage::app()->getStore($storeId)->getCurrentCurrencyCode();
?>

<script type="text/javascript">
    var selLang;
    var selCurrency;
    var selRegion;
    var selLangUrl;

    function setLang(v) {
        selLang = v.id;
        selLangUrl = v.href;
        return false;
    }

    function setCurrency(v) {
        selCurrency = v.id;
        return false;
    }

    function setRegion(v) {
        selRegion = v.value;
        return false;
    }

    function getLang() {

        if (selLang == undefined) {
            selLang = null;
        }
        return selLang;
    }

    function getLangUrl() {
        if (selLangUrl == undefined) {
            selLangUrl = null;
        }
        return selLangUrl;
    }

    function getCurrency() {

        if (selCurrency == undefined) {
            selCurrency = null;
        }

        return selCurrency;
    }

    function getRegion() {

        if (selRegion == undefined) {
            selRegion = null;
        }
        return selRegion;
    }

    function submitTabSelected(req) {

        var settings;

        if (req.id == "save_lang") {
            settings = getLang() + "," + getCurrency() + "," + getRegion() + "," + getLangUrl();
        }

        if (req.id == "save_currency") {
            settings = getLang() + "," + getCurrency() + "," + getRegion() + "," + getLangUrl();
        }

        if (req.id == "save_region") {
            settings = getLang() + "," + getCurrency() + "," + getRegion() + "," + getLangUrl();
        }

        if (req.id == "save_all") {
            settings = getLang() + "," + getCurrency() + "," + getRegion() + "," + getLangUrl();
        }

        jQuery.ajax({
            url: "<?php echo $this->getUrl('geoipdefaultlanguage/index/initAjax') ?>",
            type: "POST",
            data: {initAjax: true, type: req.id, settings: settings},
            success: function (data) {
                if (data !== 'undefined') {//alert(data);return false;
                    //window.location.href = data;
                    var loc = window.location.href;
                    var index = loc.indexOf('?');

                    if (index > 0) { // if store direct url
                        window.location = loc.substring(0, index);
                    } else if (loc.indexOf('#') > 0) { // if only div id of the pop up
                        window.location = loc.substring(0, loc.indexOf('#'));
                    } else {
                        window.location.reload(true);
                    }
                }
            },
        });

        return false;
    }


</script>

<div id="wrapper">
    <div id="my_modal" class="content">
        <!--Popup Content-->
        <div class="geoip_popup">
            <div class="content">

                <!--Tabs-->
                <div class="tabs">
                    <div class="detail_tabs">
                        <div id="tabs">
                            <div id="tab-container" class='tab-container'>
                                <ul class='etabs'>
                                    <li class='tab'><a href="#language"><?php echo $_helper->__('Language') ?></a></li>
                                    <li class='tab'><a href="#currency"><?php echo $_helper->__('Currency') ?></a></li>
                                </ul>
                                <div class='panel-container'>
                                    <div id="language" class="language">

                                        <div class="left_side">
                                            <h4><?php echo $_helper->__('Choose your Language'); ?>:</h4>
                                            <ul id="lang">
                                                <?php
                                                $stores = Mage::getModel('core/store')->getCollection()
                                                        ->addFieldToFilter('group_id', Mage::app()->getStore()->getGroupId());
                                                ?>
                                                <?php foreach ($stores as $_store): ?>
                                                    <li>
                                                        <a href="<?php echo $_store->getCurrentUrl(); ?>" id="<?php echo $_store->getId(); ?>" onClick="return setLang(this);" <?php if (Mage::app()->getStore()->getCode() == $_store->getCode()): ?>class="active" <?php endif; ?>>
                                                            <?php echo $_store->getName() ?>
                                                        </a>
                                                        <div>
                                                            <p><?php echo $_helper->__('View the site in'); ?> <?php echo $_store->getName() ?>. </p> 
                                                        </div>
                                                    </li>

                                                <?php endforeach; ?>
                                            </ul>
                                        </div>
                                        <div class="clear"></div>
                                        <div class="bottom">
                                            <a href="javascript:void;" id='fme_close_btn-1' class="close_model_fme"><?php echo $_helper->__('Cancel') ?></a>
                                            <a href="javascript:void;" id="save_lang" onclick="return submitTabSelected(this);"><?php echo $_helper->__('Save') ?></a>

                                        </div>

                                        <div class="clear"></div>
                                    </div>
                                    <div id="currency" class="language">


                                        <div class="left_side">
                                            <h4><?php echo $_helper->__('Choose your Currency') ?>:</h4>
                                            <ul id="ulcurrency">
                                                <?php foreach ($allowedCurrencies as $currency): ?>
                                                
                                                    <?php 
                                                    
                                                        $selected = '';
                                                        if ($currency == $currencyCode) {
                                                            $selected = 'class="active"';
                                                        }
                                                        
                                                    ?>
                                                    <li>
                                                        <a href="#" id="<?php echo $currency; ?>"  <?php echo $selected; ?> onClick ="return setCurrency(this);">
                                                            <span><?php echo Mage::app()->getLocale()->currency($currency)->getSymbol(); ?></span> 
                                                                <?php echo Mage::app()->getLocale()->currency($currency)->getName() ?> <?php echo $currency; ?>
                                                        </a>
                                                        <div>
                                                            <p><?php echo $_helper->__('Set store currency to '); ?> <?php echo Mage::app()->getLocale()->currency($currency)->getName() ?>. </p> 
                                                        </div>
                                                    </li>
                                                <?php endforeach; ?>
                                            </ul>
                                        </div>


                                        <div class="clear"></div>
                                        <div class="bottom">
                                            <a href="javascript:void;" id='fme_close_btn-2' class="close_model_fme"><?php echo $_helper->__('Cancel') ?></a>
                                            <a href="javascript:void;" id="save_currency" onclick="return submitTabSelected(this);"><?php echo $_helper->__('Save') ?></a>

                                        </div>

                                        <div class="clear"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>             

            </div>

        </div>
    </div>



    <!-- Tabs -->
    <script type="text/javascript">
        jQuery(function () {
            jQuery('#my_modal').popup();
            
            jQuery('.close_model_fme').click(function () {
                jQuery("#my_modal_background").trigger('click');
            });
            jQuery('.my_modal_close').click(function () {
                jQuery("#my_modal_background").trigger('click');
            });
        });
    </script>
    <script src="<?php echo $this->getSkinUrl('geoipdefaultlanguage/js/jquery.easytabs.min.js') ?>" type="text/javascript"></script>
    <script type="text/javascript">jQuery.noConflict();</script>

    <?php
//$currency = new Mage_Directory_Block_Currency(); 
//$fmeStoreCurrencyCode = (Mage::app()->getStore()->getCurrentCurrencyCode())? Mage::app()->getStore()->getCurrentCurrencyCode(): 'USD'  ;
    $fmeStoreCurrencyCode = Mage::app()
            ->getStore()
            ->getCurrentCurrencyCode();


//var_dump($fmeStoreCurrencyCode);
    $fmeStoreCurrency = Mage::app()
            ->getLocale()
            ->currency($fmeStoreCurrencyCode)
            ->getSymbol() 
            . " " . 
            Mage::app()
                ->getLocale()
                ->currency($fmeStoreCurrencyCode)
            ->getName() 
            . " " . $fmeStoreCurrencyCode;
    
    $fmeStoreNameCurr = Mage::app()->getStore()->getName();
    $fmeCurrRegion = $_helper->visitorIpInfo();
    ?>

    <?php if ($this->isEnableExt()): ?>
        <?php
        $promptStatus = Mage::getModel('core/cookie')->get('prompt_status');
        ?>
        <?php if ($promptStatus != 'no'): ?>
            <!--Footer Fix Bar-->
            <div class="footer_fix_bar" id="fme_dismiss">
                <div class="inner_container">
                    <div class="left">
                        <p><?php echo Mage::getStoreConfig('geoipdefaultlanguage/basic/prompt_text') ?>:</p>
                        <p><span><?php echo $fmeStoreNameCurr . ", " . $fmeStoreCurrency . ", " . $fmeCurrRegion["cn"] ?></span></p>
                    </div>
                    <div class="right">
                        <a href="<?php echo $_helper->getAnyStore()->getHomeUrl(); ?>" onclick="return setSessionRefresh(true, true, <?php echo Mage::helper("geoipdefaultlanguage")->getAnyStore()->getId(); ?>);"><?php echo $_helper->__('No thanks') ?></a>
                        <a href="#" onclick="return setSessionRefresh(true, false);"><?php echo $_helper->__('Okay') ?></a>

                    </div>
                </div>
            </div>
        <?php endif; ?>
    <?php endif; ?>
</div>
<a class="my_modal_open"><?php echo $fmeStoreNameCurr . ", " . $fmeStoreCurrency . ", " . $fmeCurrRegion["cn"] ?> </a>


<script type="text/javascript">
    //Tabs Function

    jQuery(document).ready(function () {

        jQuery('#tab-container').easytabs();


        jQuery('#lang li').on('click', function () {
            jQuery('#lang li div').hide();
            jQuery(this).find('div').show()
        });
        
        jQuery('#ulcurrency li').on('click', function () {
            jQuery('#ulcurrency li div').hide();
            jQuery(this).find('div').show()
        });

    });

    function dismiss() {
        return jQuery("#fme_dismiss").fadeOut("fast");
    }

    function setSessionRefresh(hidPrompt, desCookie, storeId) {
        jQuery.ajax({
            url: "<?php echo $this->getUrl('geoipdefaultlanguage/index/promptBox') ?>",
            type: "POST",
            data: {hid_prompt: hidPrompt, des_cookie: desCookie, store_id: storeId},
            success: function (data) {
                if (data == 1) {
                    jQuery("#fme_dismiss").fadeOut("fast");
                    if (desCookie) {
                        window.location.reload(true);
                    }
                }
            },
        });
        return false;
    }
</script>
