<?php
/**
 * Geoip Default Store extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   FME
 * @package    Geoipdefaultstore
 * @author     R.Rao <rafay.tahir@unitedsol.net>
 * @copyright  Copyright 2010 © free-magentoextensions.com All right reserved
 */
?>
<?php
$id = $this->getRequest()->getParam('id');
$flagWidth = 'width = "25px" height="15px"';
$_helper = Mage::helper('geoipdefaultlanguage');

//get Countries names from cc table
$results = $_helper->getCountries();

//get Blocked countries from table
$aclcountries = $_helper->getGroupedCountries($id);

$flagsUrl = $this->getSkinUrl('images/geoipflags/');
?>
<script type="text/javascript">
    var $j = jQuery.noConflict();

    $j(document).ready(function() {


        $j("#cabutton").live("click", checkall);
        $j("#ucabutton").live("click", uncheckall);

        $j("#africainp").live("click", checkafrica);
        $j("#asiainp").live("click", checkasia);
        $j("#europeinp").live("click", checkeurope);
        $j("#namericainp").live("click", checknamerica);
        $j("#oceaniainp").live("click", checkoceania);
        $j("#samericainp").live("click", checksamerica);
        $j("#otherinp").live("click", checkothers);

        $j(".test_left ul").accordion();

    });

    function checkafrica() {
        if ($j('#africainp').attr('checked'))
            $j('.africacbox').attr('checked', true);
        else
            $j('.africacbox').attr('checked', false);
    }


    function checkasia() {
        if ($j('#asiainp').attr('checked'))
            $j('.asiacbox').attr('checked', true);
        else
            $j('.asiacbox').attr('checked', false);
    }

    function checkeurope() {
        if ($j('#europeinp').attr('checked'))
            $j('.europecbox').attr('checked', true);
        else
            $j('.europecbox').attr('checked', false);
    }

    function checknamerica() {
        if ($j('#namericainp').attr('checked'))
            $j('.namericacbox').attr('checked', true);
        else
            $j('.namericacbox').attr('checked', false);
    }


    function checkoceania() {
        if ($j('#oceaniainp').attr('checked'))
            $j('.oceaniacbox').attr('checked', true);
        else
            $j('.oceaniacbox').attr('checked', false);
    }

    function checksamerica() {
        if ($j('#samericainp').attr('checked'))
            $j('.samericacbox').attr('checked', true);
        else
            $j('.samericacbox').attr('checked', false);
    }

    function checkothers() {
        if ($j('#otherinp').attr('checked'))
            $j('.othercbox').attr('checked', true);
        else
            $j('.othercbox').attr('checked', false);
    }

    function checkall() {

        //alert("checked");
        $j('.cboxinput').attr('checked', true);

        $j('#africainp').attr('checked', true);
        $j('#asiainp').attr('checked', true);
        $j('#europeinp').attr('checked', true);
        $j('#namericainp').attr('checked', true);
        $j('#oceaniainp').attr('checked', true);
        $j('#samericainp').attr('checked', true);
        $j('#otherinp').attr('checked', true);

    }

    function uncheckall() {


        $j('.cboxinput').attr('checked', false);

        $j('#africainp').attr('checked', false);
        $j('#asiainp').attr('checked', false);
        $j('#europeinp').attr('checked', false);
        $j('#namericainp').attr('checked', false);
        $j('#oceaniainp').attr('checked', false);
        $j('#samericainp').attr('checked', false);
        $j('#otherinp').attr('checked', false);
    }
</script>


<?php
$main_i = 0;
$africa = array();
$africacc = array();
$asia = array();
$asiacc = array();
$europe = array();
$europecc = array();
$namerica = array();
$namericacc = array();
$oceania = array();
$oceaniacc = array();
$samerica = array();
$samericacc = array();
$others = array();
$otherscc = array();


foreach ($results as $row):


    //finds the continent of a country and places it in its continent array.        
    if ($_helper->getcontinent($row["cn"]) == 1) {
        $africa[] = $row["cn"];
        $africacc[] = $row["cc"];
    } else if ($_helper->getcontinent($row["cn"]) == 2) {
        $asia[] = $row["cn"];
        $asiacc[] = $row["cc"];
    } else if ($_helper->getcontinent($row["cn"]) == 3) {
        $europe[] = $row["cn"];
        $europecc[] = $row["cc"];
    } else if ($_helper->getcontinent($row["cn"]) == 4) {
        $namerica[] = $row["cn"];
        $namericacc[] = $row["cc"];
    } else if ($_helper->getcontinent($row["cn"]) == 5) {
        $oceania[] = $row["cn"];
        $oceaniacc[] = $row["cc"];
    } else if ($_helper->getcontinent($row["cn"]) == 6) {
        $samerica[] = $row["cn"];
        $samericacc[] = $row["cc"];
    } else if ($_helper->getcontinent($row["cn"]) == 7) {
        $others[] = $row["cn"];
        $otherscc[] = $row["cc"];
    }


endforeach;
?>



<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__("Edit Countries List") ?></h4>
    </div>
    <div id="group_fields4" class="fieldset fieldset-wide">
        <div class="hor-scroll">
            <input type="hidden" name="cnid" value="<?php echo $id ?>">
            <span class="countrieslistlabel"><?php echo $this->__("NOTE: Select the country or countries to redirect its visitor(s) to the selected store.") ?></span><br/>
        </div>
    </div>
</div>


<div class="test_left">
    <ul class="accordion">

        <li>
            <div class="inp">
                <input 
                    id="africainp" 
                    name="countries_list[africa]" 
                    type="checkbox" <?php echo (isset($aclcountries['africa']) && sizeof($aclcountries['africa']) != 0) ? 'checked="checked"' : ''; ?> 
                    value="1"
                >
            </div>
            <a href="javascript:void(0)">&nbsp;&nbsp;<?php echo $this->__("AFRICA") ?></a>
            <div class="mapdiv">

                <table cellspacing="0" class="form-list">
                    <tbody>
                        <?php $i = 0; ?>
                        <?php
                        for ($x = 0; $x < sizeof($africa); $x++) {
                            $checked = false;
                            if (isset($aclcountries['africa'])) {
                                foreach ($aclcountries['africa'] as $aclc) {

                                    if (strcmp($aclc, $africa[$x]) == 0) {
                                        $checked = true;
                                    }
                                }
                            }
                            ?>
                            <?php if (($i++) % 3 == 0): ?> 
                                <tr>
                                <?php endif; ?>
                                <?php if (($i - 1) % 3 == 0): ?>      
                                    <td class="cboxflag"> 
                                        <img <?php echo $flagWidth; ?> src="<?php echo $flagsUrl . strtolower($africacc[$x]) . '.png'; ?>" alt="<?php echo $africa[$x]; ?>" /></td>
                                    <td class="cboxtd">
                                        <input class="cboxinput africacbox" type="checkbox" name="countries_list[africa][]" <?php if ($checked) echo "checked=\"checked\""; ?> value="<?php echo $africa[$x]; ?>">
                                    </td>
                                    <td class="cboxlabel"><?php echo $africa[$x]; ?></td>
                                <?php endif; ?>    



                                <?php if (($i - 1) % 3 == 1): ?>      
                                    <td class="cboxflag"> <img <?php echo $flagWidth; ?> src="<?php echo $flagsUrl . strtolower($africacc[$x]) . '.png'; ?>" alt="<?php echo $africa[$x]; ?>" /></td>
                                    <td class="cboxtd">
                                        <input class="cboxinput africacbox" type="checkbox" name="countries_list[africa][]" <?php if ($checked) echo "checked=\"checked\""; ?> value="<?php echo $africa[$x]; ?>">
                                    </td>
                                    <td class="cboxlabel"><?php echo $africa[$x]; ?></td>
                                <?php endif; ?>    



                                <?php if (($i - 1) % 3 == 2): ?>      
                                    <td class="cboxflag"> <img <?php echo $flagWidth; ?> src="<?php echo $flagsUrl . strtolower($africacc[$x]) . '.png'; ?>" alt="<?php echo $africa[$x]; ?>" /></td>
                                    <td class="cboxtd">
                                        <input class="cboxinput africacbox" type="checkbox" name="countries_list[africa][]" <?php if ($checked) echo "checked=\"checked\""; ?> value="<?php echo $africa[$x]; ?>">
                                    </td>
                                    <td class="cboxlabel"><?php echo $africa[$x]; ?></td>
                                <?php endif; ?>    


                                <?php if (($i) == sizeof($africa) && ($i) % 3 == 1): ?>
                                    <td></td>
                                    <td></td>
                                    <td></td>

                                    <td></td>
                                    <td></td>
                                    <td></td>
                                <?php endif; ?>  


                                <?php if (($i) == sizeof($africa) && ($i) % 3 == 2): ?>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                <?php endif; ?>      





                                <?php if (($i) % 3 == 0): ?>
                                </tr>    
                            <?php endif; ?> 




                        <?php } ?>
                    </tbody>
                </table>

            </div>
        </li>



        <li>
            <div class="inp">
                <input 
                    id="asiainp" 
                    name="countries_list[asia]" 
                    type="checkbox" <?php echo (isset($aclcountries['asia']) && sizeof($aclcountries['asia']) != 0) ? 'checked="checked"' : ''; ?> 
                    value="2"
                >
            </div>
            <a href="javascript:void(0)">&nbsp;&nbsp;<?php echo $this->__('ASIA') ?></a>
            <div class="mapdiv">

                <table cellspacing="0" class="form-list">
                    <tbody>
                        <?php $i = 0; ?>
                        <?php
                        for ($x = 0; $x < sizeof($asia); $x++) {
                            $checked = false;
                            if (isset($aclcountries['asia'])) {
                                foreach ($aclcountries['asia'] as $aclc) {

                                    if (strcmp($aclc, $asia[$x]) == 0) {

                                        $checked = true;
                                    }
                                }
                            }
                            ?>
                            <?php if (($i++) % 3 == 0): ?> 
                                <tr>
                                <?php endif; ?>
                                <?php if (($i - 1) % 3 == 0): ?>      
                                    <td class="cboxflag"> <img <?php echo $flagWidth; ?> src="<?php echo $flagsUrl . strtolower($asiacc[$x]) . '.png'; ?>" alt="<?php echo $asia[$x]; ?>" /></td>
                                    <td class="cboxtd">
                                        <input class="cboxinput asiacbox" type="checkbox" name="countries_list[asia][]" <?php if ($checked) echo "checked=\"checked\""; ?> value="<?php echo $asia[$x]; ?>">
                                    </td>
                                    <td class="cboxlabel"><?php echo $asia[$x]; ?></td>
                                <?php endif; ?>    



                                <?php if (($i - 1) % 3 == 1): ?>      
                                    <td class="cboxflag"> <img <?php echo $flagWidth; ?> src="<?php echo $flagsUrl . strtolower($asiacc[$x]) . '.png'; ?>" alt="<?php echo $asia[$x]; ?>" /></td>
                                    <td class="cboxtd">
                                        <input class="cboxinput asiacbox" type="checkbox" name="countries_list[asia][]" <?php if ($checked) echo "checked=\"checked\""; ?> value="<?php echo $asia[$x]; ?>">
                                    </td>
                                    <td class="cboxlabel"><?php echo $asia[$x]; ?></td>
                                <?php endif; ?>    



                                <?php if (($i - 1) % 3 == 2): ?>      
                                    <td class="cboxflag"> <img <?php echo $flagWidth; ?> src="<?php echo $flagsUrl . strtolower($asiacc[$x]) . '.png'; ?>" alt="<?php echo $asia[$x]; ?>" /></td>
                                    <td class="cboxtd">
                                        <input class="cboxinput asiacbox" type="checkbox" name="countries_list[asia][]" <?php if ($checked) echo "checked=\"checked\""; ?> value="<?php echo $asia[$x]; ?>">
                                    </td>
                                    <td class="cboxlabel"><?php echo $asia[$x]; ?></td>
                                <?php endif; ?>    


                                <?php if (($i) == sizeof($asia) && ($i) % 3 == 1): ?>
                                    <td></td>
                                    <td></td>
                                    <td></td>

                                    <td></td>
                                    <td></td>
                                    <td></td>
                                <?php endif; ?>  


                                <?php if (($i) == sizeof($asia) && ($i) % 3 == 2): ?>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                <?php endif; ?>      


                                <?php if (($i) % 3 == 0): ?>
                                </tr>    
                            <?php endif; ?> 




                        <?php } ?>
                    </tbody>
                </table>

            </div>
        </li>







        <li>
            <div class="inp">
                <input 
                    id="europeinp" 
                    name ="countries_list[europe]" 
                    type="checkbox" <?php echo (isset($aclcountries['europe']) && sizeof($aclcountries['europe']) != 0) ? 'checked="checked"' : ''; ?> 
                    value="3"
                >
            </div>
            <a href="javascript:void(0)">&nbsp;&nbsp;<?php echo $this->__('EUROPE') ?></a>
            <div class="mapdiv">

                <table cellspacing="0" class="form-list">
                    <tbody>
                        <?php $i = 0; ?>
                        <?php
                        for ($x = 0; $x < sizeof($europe); $x++) {
                            $checked = false;
                            if (isset($aclcountries['europe'])) {
                                foreach ($aclcountries['europe'] as $aclc) {


                                    if (strcmp($aclc, $europe[$x]) == 0) {
                                        $checked = true;
                                    }
                                }
                            }
                            ?>
                            <?php if (($i++) % 3 == 0): ?> 
                                <tr>
                                <?php endif; ?>
                                <?php if (($i - 1) % 3 == 0): ?>      
                                    <td class="cboxflag"> <img <?php echo $flagWidth; ?> src="<?php echo $flagsUrl . strtolower($europecc[$x]) . '.png'; ?>" alt="<?php echo $europe[$x]; ?>" /></td>
                                    <td class="cboxtd">
                                        <input class="cboxinput europecbox" type="checkbox" name="countries_list[europe][]" <?php if ($checked) echo "checked=\"checked\""; ?> value="<?php echo $europe[$x]; ?>">
                                    </td>
                                    <td class="cboxlabel"><?php echo $europe[$x]; ?></td>
                                <?php endif; ?>    



                                <?php if (($i - 1) % 3 == 1): ?>      
                                    <td class="cboxflag"> <img <?php echo $flagWidth; ?> src="<?php echo $flagsUrl . strtolower($europecc[$x]) . '.png'; ?>" alt="<?php echo $europe[$x]; ?>" /></td>
                                    <td class="cboxtd">
                                        <input class="cboxinput europecbox" type="checkbox" name="countries_list[europe][]" <?php if ($checked) echo "checked=\"checked\""; ?> value="<?php echo $europe[$x]; ?>">
                                    </td>
                                    <td class="cboxlabel"><?php echo $europe[$x]; ?></td>
                                <?php endif; ?>    



                                <?php if (($i - 1) % 3 == 2): ?>      
                                    <td class="cboxflag"> <img <?php echo $flagWidth; ?> src="<?php echo $flagsUrl . strtolower($europecc[$x]) . '.png'; ?>" alt="<?php echo $europe[$x]; ?>" /></td>
                                    <td class="cboxtd">
                                        <input class="cboxinput europecbox" type="checkbox" name="countries_list[europe][]" <?php if ($checked) echo "checked=\"checked\""; ?> value="<?php echo $europe[$x]; ?>">
                                    </td>
                                    <td class="cboxlabel"><?php echo $europe[$x]; ?></td>
                                <?php endif; ?>    


                                <?php if (($i) == sizeof($europe) && ($i) % 3 == 1): ?>
                                    <td></td>
                                    <td></td>
                                    <td></td>

                                    <td></td>
                                    <td></td>
                                    <td></td>
                                <?php endif; ?>  


                                <?php if (($i) == sizeof($europe) && ($i) % 3 == 2): ?>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                <?php endif; ?>      





                                <?php if (($i) % 3 == 0): ?>
                                </tr>    
                            <?php endif; ?> 




                        <?php } ?>
                    </tbody>
                </table>

            </div>
        </li>







        <li>
            <div class="inp">
                <input 
                    id="namericainp" 
                    name="countries_list[north_america]" 
                    type="checkbox"  <?php echo (isset($aclcountries['north_america']) && sizeof($aclcountries['north_america']) != 0) ? 'checked="checked"' : ''; ?> 
                    value="4"
                >
            </div>
            <a href="javascript:void(0)">&nbsp;&nbsp;<?php echo $this->__('NORTH AMERICA') ?></a>
            <div class="mapdiv">

                <table cellspacing="0" class="form-list">
                    <tbody>
                        <?php $i = 0; ?>
                        <?php
                        for ($x = 0; $x < sizeof($namerica); $x++) {
                            $checked = false;
                            if (isset($aclcountries['north_america'])) {
                                foreach ($aclcountries['north_america'] as $aclc) {


                                    if (strcmp($aclc, $namerica[$x]) == 0) {
                                        $checked = true;
                                    }
                                }
                            }
                            ?>
                            <?php if (($i++) % 3 == 0): ?> 
                                <tr>
                                <?php endif; ?>
                                <?php if (($i - 1) % 3 == 0): ?>      
                                    <td class="cboxflag"> <img <?php echo $flagWidth; ?> src="<?php echo $flagsUrl . strtolower($namericacc[$x]) . '.png'; ?>" alt="<?php echo $namerica[$x]; ?>" /></td>
                                    <td class="cboxtd">
                                        <input class="cboxinput namericacbox" type="checkbox" name="countries_list[north_america][]" <?php if ($checked) echo "checked=\"checked\""; ?> value="<?php echo $namerica[$x]; ?>">
                                    </td>
                                    <td class="cboxlabel"><?php echo $namerica[$x]; ?></td>
                                <?php endif; ?>    



                                <?php if (($i - 1) % 3 == 1): ?>      
                                    <td class="cboxflag"> <img <?php echo $flagWidth; ?> src="<?php echo $flagsUrl . strtolower($namericacc[$x]) . '.png'; ?>" alt="<?php echo $namerica[$x]; ?>" /></td>
                                    <td class="cboxtd">
                                        <input class="cboxinput namericacbox" type="checkbox" name="countries_list[north_america][]" <?php if ($checked) echo "checked=\"checked\""; ?> value="<?php echo $namerica[$x]; ?>">
                                    </td>
                                    <td class="cboxlabel"><?php echo $namerica[$x]; ?></td>
                                <?php endif; ?>    



                                <?php if (($i - 1) % 3 == 2): ?>      
                                    <td class="cboxflag"> <img src="<?php echo $flagsUrl . strtolower($namericacc[$x]) . '.png'; ?>" alt="<?php echo $namerica[$x]; ?>" /></td>
                                    <td class="cboxtd">
                                        <input class="cboxinput namericacbox" type="checkbox" name="countries_list[north_america][]" <?php if ($checked) echo "checked=\"checked\""; ?> value="<?php echo $namerica[$x]; ?>">
                                    </td>
                                    <td class="cboxlabel"><?php echo $namerica[$x]; ?></td>
                                <?php endif; ?>    


                                <?php if (($i) == sizeof($namerica) && ($i) % 3 == 1): ?>
                                    <td></td>
                                    <td></td>
                                    <td></td>

                                    <td></td>
                                    <td></td>
                                    <td></td>


                                <?php endif; ?>  


                                <?php if (($i) == sizeof($namerica) && ($i) % 3 == 2): ?>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                <?php endif; ?>      





                                <?php if (($i) % 3 == 0): ?>
                                </tr>    
                            <?php endif; ?> 




                        <?php } ?>
                    </tbody>
                </table>

            </div>
        </li>

        <li>
            <div class="inp">
                <input 
                    id="oceaniainp" 
                    name="countries_list[oceania]" 
                    type="checkbox" <?php echo (isset($aclcountries['oceania']) && sizeof($aclcountries['oceania']) != 0) ? 'checked="checked"' : ''; ?> 
                    value="5"
                >
            </div>
            <a href="javascript:void(0)">&nbsp;&nbsp;<?php echo $this->__('OCEANIA') ?></a>
            <div class="mapdiv">

                <table cellspacing="0" class="form-list">
                    <tbody>
                        <?php $i = 0; ?>
                        <?php
                        for ($x = 0; $x < sizeof($oceania); $x++) {
                            $checked = false;
                            if (isset($aclcountries['oceania'])) {
                                foreach ($aclcountries['oceania'] as $aclc) {


                                    if (strcmp($aclc, $oceania[$x]) == 0) {
                                        $checked = true;
                                    }
                                }
                            }
                            ?>
                            <?php if (($i++) % 3 == 0): ?> 
                                <tr>
                                <?php endif; ?>
                                <?php if (($i - 1) % 3 == 0): ?>      
                                    <td class="cboxflag"> <img <?php echo $flagWidth; ?> src="<?php echo $flagsUrl . strtolower($oceaniacc[$x]) . '.png'; ?>" alt="<?php echo $oceania[$x]; ?>" /></td>
                                    <td class="cboxtd">
                                        <input class="cboxinput oceaniacbox" type="checkbox" name="countries_list[oceania][]" <?php if ($checked) echo "checked=\"checked\""; ?> value="<?php echo $oceania[$x]; ?>">
                                    </td>
                                    <td class="cboxlabel"><?php echo $oceania[$x]; ?></td>
                                <?php endif; ?>    



                                <?php if (($i - 1) % 3 == 1): ?>      
                                    <td class="cboxflag"> <img <?php echo $flagWidth; ?> src="<?php echo $flagsUrl . strtolower($oceaniacc[$x]) . '.png'; ?>" alt="<?php echo $oceania[$x]; ?>" /></td>
                                    <td class="cboxtd">
                                        <input class="cboxinput oceaniacbox" type="checkbox" name="countries_list[oceania][]" <?php if ($checked) echo "checked=\"checked\""; ?> value="<?php echo $oceania[$x]; ?>">
                                    </td>
                                    <td class="cboxlabel"><?php echo $oceania[$x]; ?></td>
                                <?php endif; ?>    



                                <?php if (($i - 1) % 3 == 2): ?>      
                                    <td class="cboxflag"> <img <?php echo $flagWidth; ?> src="<?php echo $flagsUrl . strtolower($oceaniacc[$x]) . '.png'; ?>" alt="<?php echo $oceania[$x]; ?>" /></td>
                                    <td class="cboxtd">
                                        <input class="cboxinput oceaniacbox" type="checkbox" name="countries_list[oceania][]" <?php if ($checked) echo "checked=\"checked\""; ?> value="<?php echo $oceania[$x]; ?>">
                                    </td>
                                    <td class="cboxlabel"><?php echo $oceania[$x]; ?></td>
                                <?php endif; ?>    


                                <?php if (($i) == sizeof($oceania) && ($i) % 3 == 1): ?>
                                    <td></td>
                                    <td></td>
                                    <td></td>

                                    <td></td>
                                    <td></td>
                                    <td></td>
                                <?php endif; ?>  


                                <?php if (($i) == sizeof($oceania) && ($i) % 3 == 2): ?>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                <?php endif; ?>      





                                <?php if (($i) % 3 == 0): ?>
                                </tr>    
                            <?php endif; ?> 




                        <?php } ?>
                    </tbody>
                </table>

            </div>
        </li>







        <li>
            <div class="inp">
                <input 
                    id="samericainp" 
                    name="countries_list[south_america]" 
                    type="checkbox" <?php echo (isset($aclcountries['south_america']) && sizeof($aclcountries['south_america']) != 0) ? 'checked="checked"' : ''; ?> 
                    value="6"
                >
            </div>
            <a href="javascript:void(0)">&nbsp;&nbsp;<?php echo $this->__('SOUTH AMERICA') ?></a>
            <div class="mapdiv">

                <table cellspacing="0" class="form-list">
                    <tbody>
                        <?php $i = 0; ?>
                        <?php
                        for ($x = 0; $x < sizeof($samerica); $x++) {
                            $checked = false;
                            if (isset($aclcountries['south_america'])) {
                                foreach ($aclcountries['south_america'] as $aclc) {

                                    if (strcmp($aclc, $samerica[$x]) == 0) {
                                        $checked = true;
                                    }
                                }
                            }
                            ?>
                            <?php if (($i++) % 3 == 0): ?> 
                                <tr>
                                <?php endif; ?>
                                <?php if (($i - 1) % 3 == 0): ?>      
                                    <td class="cboxflag"> <img <?php echo $flagWidth; ?> src="<?php echo $flagsUrl . strtolower($samericacc[$x]) . '.png'; ?>" alt="<?php echo $samerica[$x]; ?>" /></td>
                                    <td class="cboxtd">
                                        <input class="cboxinput samericacbox" type="checkbox" name="countries_list[south_america][]" <?php if ($checked) echo "checked=\"checked\""; ?> value="<?php echo $samerica[$x]; ?>">
                                    </td>
                                    <td class="cboxlabel"><?php echo $samerica[$x]; ?></td>
                                <?php endif; ?>    



                                <?php if (($i - 1) % 3 == 1): ?>      
                                    <td class="cboxflag"> <img <?php echo $flagWidth; ?> src="<?php echo $flagsUrl . strtolower($samericacc[$x]) . '.png'; ?>" alt="<?php echo $samerica[$x]; ?>" /></td>
                                    <td class="cboxtd">
                                        <input class="cboxinput samericacbox" type="checkbox" name="countries_list[south_america][]" <?php if ($checked) echo "checked=\"checked\""; ?> value="<?php echo $samerica[$x]; ?>">
                                    </td>
                                    <td class="cboxlabel"><?php echo $samerica[$x]; ?></td>
                                <?php endif; ?>    



                                <?php if (($i - 1) % 3 == 2): ?>      
                                    <td class="cboxflag"> <img <?php echo $flagWidth; ?> src="<?php echo $flagsUrl . strtolower($samericacc[$x]) . '.png'; ?>" alt="<?php echo $samerica[$x]; ?>" /></td>
                                    <td class="cboxtd">
                                        <input class="cboxinput samericacbox" type="checkbox" name="countries_list[south_america][]" <?php if ($checked) echo "checked=\"checked\""; ?> value="<?php echo $samerica[$x]; ?>">
                                    </td>
                                    <td class="cboxlabel"><?php echo $samerica[$x]; ?></td>
                                <?php endif; ?>    


                                <?php if (($i) == sizeof($samerica) && ($i) % 3 == 1): ?>
                                    <td></td>
                                    <td></td>
                                    <td></td>

                                    <td></td>
                                    <td></td>
                                    <td></td>
                                <?php endif; ?>  


                                <?php if (($i) == sizeof($samerica) && ($i) % 3 == 2): ?>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                <?php endif; ?>      





                                <?php if (($i) % 3 == 0): ?>
                                </tr>    
                            <?php endif; ?> 




                        <?php } ?>
                    </tbody>
                </table>

            </div>
        </li>

        <li>
            <div class="inp">
                <input 
                    id="otherinp" 
                    name="countries_list[others]" 
                    type="checkbox" <?php echo (isset($aclcountries['others']) && sizeof($aclcountries['others']) != 0) ? 'checked="checked"' : ''; ?> 
                    value="7"
                >
            </div>
            <a href="javascript:void(0)">&nbsp;&nbsp;<?php echo $this->__('OTHERS') ?></a>
            <div class="mapdiv">

                <table cellspacing="0" class="form-list">
                    <tbody>
                        <?php $i = 0; //foreach($results as $row):  ?>
                        <?php
                        for ($x = 0; $x < sizeof($others); $x++) {
                            $checked = false;
                            if (isset($aclcountries['others'])) {
                                foreach ($aclcountries['others'] as $aclc) {


                                    if (strcmp($aclc, $others[$x]) == 0) {
                                        $checked = true;
                                    }
                                }
                            }
                            ?>
                            <?php if (($i++) % 3 == 0): ?> 
                                <tr>
                                <?php endif; ?>
                                <?php if (($i - 1) % 3 == 0): ?>      
                                    <td class="cboxflag"> <img <?php echo $flagWidth; ?> src="<?php echo $flagsUrl . strtolower($otherscc[$x]) . '.png'; ?>" alt="<?php echo $others[$x]; ?>" /></td>
                                    <td class="cboxtd">
                                        <input class="cboxinput othercbox" type="checkbox" name="countries_list[others][]" <?php if ($checked) echo "checked=\"checked\""; ?> value="<?php echo $others[$x]; ?>">
                                    </td>
                                    <td class="cboxlabel"><?php echo $others[$x]; ?></td>
                                <?php endif; ?>    



                                <?php if (($i - 1) % 3 == 1): ?>      
                                    <td class="cboxflag"> <img <?php echo $flagWidth; ?> src="<?php echo $flagsUrl . strtolower($otherscc[$x]) . '.png'; ?>" alt="<?php echo $others[$x]; ?>" /></td>
                                    <td class="cboxtd">
                                        <input class="cboxinput othercbox" type="checkbox" name="countries_list[others][]" <?php if ($checked) echo "checked=\"checked\""; ?> value="<?php echo $others[$x]; ?>">
                                    </td>
                                    <td class="cboxlabel"><?php echo $others[$x]; ?></td>
                                <?php endif; ?>    



                                <?php if (($i - 1) % 3 == 2): ?>      
                                    <td class="cboxflag"> <img <?php echo $flagWidth; ?> src="<?php echo $flagsUrl . strtolower($otherscc[$x]) . '.png'; ?>" alt="<?php echo $others[$x]; ?>" /></td>
                                    <td class="cboxtd">
                                        <input class="cboxinput othercbox" type="checkbox" name="countries_list[others][]" <?php if ($checked) echo "checked=\"checked\""; ?> value="<?php echo $others[$x]; ?>">
                                    </td>
                                    <td class="cboxlabel"><?php echo $others[$x]; ?></td>
                                <?php endif; ?>    


                                <?php if (($i - 1) == sizeof($others) && ($i - 1) % 3 == 1): ?>
                                    <td></td>
                                    <td></td>
                                    <td></td>

                                    <td></td>
                                    <td></td>
                                    <td></td>
                                <?php endif; ?>  


                                <?php if (($i - 1) == sizeof($others) && ($i - 1) % 3 == 2): ?>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                <?php endif; ?>      





                                <?php if (($i) % 3 == 0): ?>
                                </tr>    
                            <?php endif; ?> 




                        <?php } ?>
                    </tbody>
                </table>

            </div>
        </li>


    </ul>
</div>




